const fs=require('fs'),vm=require('vm'),assert=require('assert/strict'),YAML=require('yaml');
class Empty{}; class TFile{constructor(path){this.path=path;this.basename=path.split('/').pop().replace(/\.md$/,'');this.extension='md';this.stat={mtime:1};}}
const ob=new Proxy({ItemView:Empty,Plugin:Empty,Modal:Empty,PluginSettingTab:Empty,FuzzySuggestModal:Empty,TFile,TFolder:Empty,Notice:Empty,parseYaml:YAML.parse,stringifyYaml:YAML.stringify,normalizePath:p=>p}, {get:(t,p)=>t[p]||Empty});
const ctx={require:n=>{if(n==='obsidian')return ob;throw Error(n)},module:{exports:{}},console,Date,Map,Set,crypto,window:{},clearTimeout,setTimeout};
vm.createContext(ctx);vm.runInContext(fs.readFileSync(__dirname+'/../.obsidian/plugins/dandan-workstation-home/main.js','utf8')+'\nmodule.exports.test={parseJournal,serializeJournal,journalNewContent,PaperJournalView,buildDefaultDiaryContent};',ctx);
const {parseJournal,serializeJournal,journalNewContent,PaperJournalView,buildDefaultDiaryContent}=ctx.module.exports.test;
let count=0;function test(name,fn){return Promise.resolve().then(fn).then(()=>{count++;console.log('PASS '+name)});}
function fakeView(source){const v=new PaperJournalView({},{});let stored=source;v.path='日记/2026-10-06.md';v.source=source;v.model=parseJournal(source);v.model.title='测试标题';v.dirty=true;v.revision=1;v.status={textContent:''};v.plugin={journalDrafts:{},saveJournalDrafts:async()=>{}};v.app={vault:{getAbstractFileByPath:p=>new TFile(p),process:async(f,cb)=>{stored=cb(stored)},create:async()=>{}}};v.renderStack=async()=>{};return {v,get:()=>stored,set:x=>stored=x};}
(async()=>{
 await test('六项新模板与手写天气',()=>{const s=buildDefaultDiaryContent({year:2026,month:10,day:6},'自动天气');const m=parseJournal(s);assert.equal(m.weather,'');assert.equal(m.title,'');for(const h of ['标题:','心情:','天气:','## 今天有什么要写的','## 今天学到的东西','## 今天有什么要反思的'])assert.ok(s.includes(h),h);});
 await test('旧格式自由记录与两项章节兼容',()=>{const s='---\n日期: 2026-10-06\n心情: \"平静\"\n天气: \"晴\"\n---\n\n保留的自由记录\n\n## 今天最大的收获是什么？\n学到的内容\n\n## 有什么需要反思的？\n反思内容';const m=parseJournal(s);assert.equal(m.parts[0],'保留的自由记录');assert.equal(m.parts[1],'学到的内容');assert.equal(m.parts[2],'反思内容');assert.ok(serializeJournal(m,'2026-10-06').includes('保留的自由记录'));});
 await test('未知属性、Markdown、代码块与旧标题兼容',()=>{const s='---\n标签: [日记, 阅读]\n自定义:\n  数字: 3\n心情: "平静: 开心"\n---\n\n## 今天最大的收获是什么？\n学到A\n```md\n## 今天有什么要反思的\n代码示例\n```\n## 其他笔记\n- [ ] 待办\n![[图片.png]]\n## 有什么需要反思的？\n反思B';const m=parseJournal(s);assert.ok(m.parts[1].includes('代码示例'));assert.equal(m.parts[2],'反思B');const out=serializeJournal(m,'2026-10-06');assert.ok(out.includes('![[图片.png]]'));assert.equal(parseJournal(out).meta['自定义']['数字'],3);assert.equal(parseJournal(out).mood,'平静: 开心');assert.equal(parseJournal(out).meta['标签'].length,2);});
 await test('自动保存回写六字段',async()=>{const f=fakeView(journalNewContent({year:2026,month:10,day:6}));f.v.model.weather='晴，有微风';f.v.model.mood='平静';f.v.model.parts=['写的内容','学到的内容','反思内容'];assert.equal(await f.v.flush(),true);const m=parseJournal(f.get());assert.equal(m.weather,'晴，有微风');assert.equal(m.title,'测试标题');assert.equal(m.parts[2],'反思内容');assert.equal(f.v.dirty,false);assert.equal(Object.keys(f.v.plugin.journalDrafts).length,0);});
 await test('外部修改不会被自动保存覆盖，草稿保留',async()=>{const f=fakeView('原来的内容');f.set('其他窗口修改后的内容');assert.equal(await f.v.flush(),false);assert.equal(f.get(),'其他窗口修改后的内容');assert.equal(f.v.dirty,true);assert.ok(f.v.plugin.journalDrafts[f.v.path]);assert.ok(f.v.status.textContent.includes('其他窗口'));});
 await test('保存期间继续输入不会丢失最后一次修改',async()=>{const f=fakeView('旧内容');let calls=0;f.v.app.vault.process=async(file,cb)=>{calls++;if(calls===1){const output=cb(f.get());f.set(output);f.v.model.parts[0]='保存期间的新内容';f.v.revision++;}else f.set(cb(f.get()));};assert.equal(await f.v.flush(),true);assert.equal(calls,2);assert.equal(parseJournal(f.get()).parts[0],'保存期间的新内容');});
 console.log(`${count} tests passed`);
})().catch(e=>{console.error(e);process.exitCode=1});
